const internetSlang = [
  'AMA - Ask Me Anything ❓',
  'Bae - Before Anyone Else ❤️',
  'BFF - Best Friends Forever 👯‍♀️',
  'BRB - Be Right Back ⏳',
  'BTW - By The Way ➡️',
  'BTAIM - Be That As It May 🤷',
  "CTN - Can't Talk Now 🤐",
  'CYE - Check Your Email 📧',
  'DM - Direct Message 📩',
  "FFS - For F***'s Sake 😤",
  'FOMO - Fear Of Missing Out 😬',
  'FTW - For The Win 🏆',
  'FWB - Friends With Benefits 😏',
  "FWIW - For What It's Worth 💭",
  'FYI - For Your Information ℹ️',
  'GG - Good Game 🎮',
  'GMV - Got My Vote 🗳️',
  'GTG - Got To Go 🚶',
  'HTH - Hope This Helps 🙏',
  'IC - I See 👀',
  "ICYDK - In Case You Didn't Know 💡",
  'ICYMI - In Case You Missed It 📰',
  "IDC - I Don't Care 🙄",
  "IDK - I Don't Know 🤔",
  'IKR - I Know, Right? 😅',
  'IMHO - In My Humble Opinion 🤔',
  'IRL - In Real Life 🌏',
  'JK - Just Kidding 😜',
  'JSYK - Just So You Know 🤓',
  'K - Okay 👍',
  'L8R - Later 👋',
  'LMAO - Laughing My A** Off 😂',
  'LMK - Let Me Know 📲',
  'LOL - Laugh Out Loud 😆',
  'NBD - No Big Deal 🤷‍♂️',
  'NSFW - Not Safe For Work 🚫',
  'NVM - Never Mind 😌',
  'OMG - Oh My Gosh 😲',
  'OTP - One True Pairing ❤️',
  'RN - Right Now 🕒',
  'ROFL - Rolling On the Floor Laughing 🤣',
  'SFW - Safe For Work ✔️',
  'SMH - Shaking My Head 🤦',
  'STFU - Shut The F*** Up 🤐',
  'SUS - Suspect 🕵️',
  'TBH - To Be Honest 🗣️',
  'THX - Thanks 🙏',
  'TMI - Too Much Information 🤯',
  'TTFN - Ta Ta For Now 👋',
  'TTYL - Talk To You Later 💬',
  'TY - Thank You 🙏',
  'W8 - Wait ⏳',
  'w/e - Whatever 🙄',
  'WNt - Why Not 🤷',
  'WYD - What You Doing? 👀',
  'YOLO - You Only Live Once 🌟',
  'ZZZ - Sleeping 😴',
]
